### ISSUE TITLE
Keine Uebung 11?

### ISSUE THREAD

**Issue by Handfeger** [trebst/compphys-2016#3]
Hallo,

auf der Website ist ein Uebungsblatt #11 vorhanden. Leider aber bisher kein Push in github. Wirft den Github-Sync von Juliabox ein wenig aus der Spur.

Liebe Gruesse

**Comment by trebst** [comment]
> auf der Website ist ein Uebungsblatt #11 vorhanden. Leider aber bisher kein Push in github. 

Done. Vielen Dank für den Hinweis,
Simon Trebst
